// Copyright (c) 2020, Frank Göldner
// All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: fragoe/reusables/v1/address.proto

package reusables

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// A full physical location of something.
type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Language in which the address is given.
	//
	// The names for country, province and city are different in different languages,
	// so you can have the same address in English and German.
	//
	// Example:
	//  - de: Deutschland / Bayern / München
	//  - en: Germany / Bavaria / Munich
	//  - fr: Allemagne / Bavière / Munich
	//
	// Language Codes
	// --------------
	// Language codes are defined by [ISO 639](https://en.wikipedia.org/wiki/ISO_639),
	// an international standard that assigns two- and three-letter codes to most
	// languages of the world.
	//
	// Examples:
	//   - "de"
	//   - "en"
	//   - "fr"
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// The country that this property is located in. The value must be an ISO 3116 uppercase
	// 2-letter country code. For example, United States is "US" and Canada is "CA".
	//
	// reference: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	// The name of the property's state, region, or province.
	Province string `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	// The name of the property's city.
	City string `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	// The property's postal code.
	PostalCode string `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	// The primary street address of the property.
	Address1 string `protobuf:"bytes,6,opt,name=address1,proto3" json:"address1,omitempty"`
	// The secondary street address of the property, if necessary.
	Address2 string `protobuf:"bytes,7,opt,name=address2,proto3" json:"address2,omitempty"`
	// The secondary street address of the property, if necessary.
	Address3 string `protobuf:"bytes,8,opt,name=address3,proto3" json:"address3,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fragoe_reusables_v1_address_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_fragoe_reusables_v1_address_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_fragoe_reusables_v1_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *Address) GetAddress2() string {
	if x != nil {
		return x.Address2
	}
	return ""
}

func (x *Address) GetAddress3() string {
	if x != nil {
		return x.Address3
	}
	return ""
}

var File_fragoe_reusables_v1_address_proto protoreflect.FileDescriptor

var file_fragoe_reusables_v1_address_proto_rawDesc = []byte{
	0x0a, 0x21, 0x66, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2f, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x66, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2e, 0x72, 0x65, 0x75, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xe4, 0x01, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f,
	0x73, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x31, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x33, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x33, 0x42,
	0x94, 0x01, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2e, 0x72,
	0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1d, 0x66, 0x72, 0x61,
	0x67, 0x6f, 0x65, 0x2f, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2f, 0x76, 0x31,
	0x3b, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0xa2, 0x02, 0x05, 0x46, 0x47, 0x52,
	0x55, 0x53, 0xaa, 0x02, 0x13, 0x46, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2e, 0x52, 0x65, 0x75, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x13, 0x46, 0x72, 0x61, 0x67, 0x6f,
	0x65, 0x5c, 0x52, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x5c, 0x56, 0x31, 0xea, 0x02,
	0x15, 0x46, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x3a, 0x3a, 0x52, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fragoe_reusables_v1_address_proto_rawDescOnce sync.Once
	file_fragoe_reusables_v1_address_proto_rawDescData = file_fragoe_reusables_v1_address_proto_rawDesc
)

func file_fragoe_reusables_v1_address_proto_rawDescGZIP() []byte {
	file_fragoe_reusables_v1_address_proto_rawDescOnce.Do(func() {
		file_fragoe_reusables_v1_address_proto_rawDescData = protoimpl.X.CompressGZIP(file_fragoe_reusables_v1_address_proto_rawDescData)
	})
	return file_fragoe_reusables_v1_address_proto_rawDescData
}

var file_fragoe_reusables_v1_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fragoe_reusables_v1_address_proto_goTypes = []interface{}{
	(*Address)(nil), // 0: fragoe.reusables.v1.Address
}
var file_fragoe_reusables_v1_address_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fragoe_reusables_v1_address_proto_init() }
func file_fragoe_reusables_v1_address_proto_init() {
	if File_fragoe_reusables_v1_address_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fragoe_reusables_v1_address_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fragoe_reusables_v1_address_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fragoe_reusables_v1_address_proto_goTypes,
		DependencyIndexes: file_fragoe_reusables_v1_address_proto_depIdxs,
		MessageInfos:      file_fragoe_reusables_v1_address_proto_msgTypes,
	}.Build()
	File_fragoe_reusables_v1_address_proto = out.File
	file_fragoe_reusables_v1_address_proto_rawDesc = nil
	file_fragoe_reusables_v1_address_proto_goTypes = nil
	file_fragoe_reusables_v1_address_proto_depIdxs = nil
}
