// Copyright (c) 2020, Frank Göldner
// All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: fragoe/reusables/v1/i18n_text.proto

package reusables

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Internationalised text.
type I18NText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Locale, consisting of language and region.
	//
	// Format:
	//     <language code>[_<country code>]
	//
	// Language Codes
	// --------------
	// Language codes are defined by [ISO 639](https://en.wikipedia.org/wiki/ISO_639),
	// an international standard that assigns two- and three-letter codes to most
	// languages of the world. Locale uses the two-letter codes to identify the target
	// language.
	//
	// Country (Region) Codes
	// ----------------------
	// Language doesn't paint the entire picture of a locale. For example, even though
	// you may use de as the locale language code, de alone doesn't tell you anything
	// about where German is spoken. Several countries use German as an official first
	// or even second language in different varieties and dialects. For this reason
	// and others, language is not always sufficient to precisely define a locale.
	//
	// Country codes are defined by [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166),
	// another international standard. It defines two- and three-letter abbreviations
	// for each country or major region in the world. In contrast to the language codes,
	// country codes are set uppercase. Locale uses the two-letter codes instead of the
	// three-letter codes that this standard also defines.
	//
	// Examples:
	//   - de
	//   - de_DE
	//   - de_CH
	Locale string `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	// The text in the specified language.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *I18NText) Reset() {
	*x = I18NText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fragoe_reusables_v1_i18n_text_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *I18NText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I18NText) ProtoMessage() {}

func (x *I18NText) ProtoReflect() protoreflect.Message {
	mi := &file_fragoe_reusables_v1_i18n_text_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I18NText.ProtoReflect.Descriptor instead.
func (*I18NText) Descriptor() ([]byte, []int) {
	return file_fragoe_reusables_v1_i18n_text_proto_rawDescGZIP(), []int{0}
}

func (x *I18NText) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *I18NText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_fragoe_reusables_v1_i18n_text_proto protoreflect.FileDescriptor

var file_fragoe_reusables_v1_i18n_text_proto_rawDesc = []byte{
	0x0a, 0x23, 0x66, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2f, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x31, 0x38, 0x6e, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x66, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2e, 0x72, 0x65,
	0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x36, 0x0a, 0x08, 0x49, 0x31,
	0x38, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x42, 0x95, 0x01, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x72, 0x61, 0x67, 0x6f,
	0x65, 0x2e, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0d,
	0x49, 0x31, 0x38, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x1d, 0x66, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2f, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0xa2, 0x02,
	0x05, 0x46, 0x47, 0x52, 0x55, 0x53, 0xaa, 0x02, 0x13, 0x46, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2e,
	0x52, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x13, 0x46,
	0x72, 0x61, 0x67, 0x6f, 0x65, 0x5c, 0x52, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x5c,
	0x56, 0x31, 0xea, 0x02, 0x15, 0x46, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x3a, 0x3a, 0x52, 0x65, 0x75,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_fragoe_reusables_v1_i18n_text_proto_rawDescOnce sync.Once
	file_fragoe_reusables_v1_i18n_text_proto_rawDescData = file_fragoe_reusables_v1_i18n_text_proto_rawDesc
)

func file_fragoe_reusables_v1_i18n_text_proto_rawDescGZIP() []byte {
	file_fragoe_reusables_v1_i18n_text_proto_rawDescOnce.Do(func() {
		file_fragoe_reusables_v1_i18n_text_proto_rawDescData = protoimpl.X.CompressGZIP(file_fragoe_reusables_v1_i18n_text_proto_rawDescData)
	})
	return file_fragoe_reusables_v1_i18n_text_proto_rawDescData
}

var file_fragoe_reusables_v1_i18n_text_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fragoe_reusables_v1_i18n_text_proto_goTypes = []interface{}{
	(*I18NText)(nil), // 0: fragoe.reusables.v1.I18nText
}
var file_fragoe_reusables_v1_i18n_text_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fragoe_reusables_v1_i18n_text_proto_init() }
func file_fragoe_reusables_v1_i18n_text_proto_init() {
	if File_fragoe_reusables_v1_i18n_text_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fragoe_reusables_v1_i18n_text_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*I18NText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fragoe_reusables_v1_i18n_text_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fragoe_reusables_v1_i18n_text_proto_goTypes,
		DependencyIndexes: file_fragoe_reusables_v1_i18n_text_proto_depIdxs,
		MessageInfos:      file_fragoe_reusables_v1_i18n_text_proto_msgTypes,
	}.Build()
	File_fragoe_reusables_v1_i18n_text_proto = out.File
	file_fragoe_reusables_v1_i18n_text_proto_rawDesc = nil
	file_fragoe_reusables_v1_i18n_text_proto_goTypes = nil
	file_fragoe_reusables_v1_i18n_text_proto_depIdxs = nil
}
