// Copyright (c) 2020, Frank Göldner
// All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: fragoe/reusables/v1/picture_link.proto

package reusables

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Object to store a picture URL and an appropriate caption.
type PictureLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Specifies the location of the picture.
	//
	// The location should be public (not behind a firewall) and should include the
	// protocol (https://).
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Defines the caption for the picture.
	Caption []*I18NText `protobuf:"bytes,2,rep,name=caption,proto3" json:"caption,omitempty"`
}

func (x *PictureLink) Reset() {
	*x = PictureLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fragoe_reusables_v1_picture_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureLink) ProtoMessage() {}

func (x *PictureLink) ProtoReflect() protoreflect.Message {
	mi := &file_fragoe_reusables_v1_picture_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureLink.ProtoReflect.Descriptor instead.
func (*PictureLink) Descriptor() ([]byte, []int) {
	return file_fragoe_reusables_v1_picture_link_proto_rawDescGZIP(), []int{0}
}

func (x *PictureLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PictureLink) GetCaption() []*I18NText {
	if x != nil {
		return x.Caption
	}
	return nil
}

var File_fragoe_reusables_v1_picture_link_proto protoreflect.FileDescriptor

var file_fragoe_reusables_v1_picture_link_proto_rawDesc = []byte{
	0x0a, 0x26, 0x66, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2f, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x6c, 0x69,
	0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x66, 0x72, 0x61, 0x67, 0x6f, 0x65,
	0x2e, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x23, 0x66,
	0x72, 0x61, 0x67, 0x6f, 0x65, 0x2f, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x69, 0x31, 0x38, 0x6e, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0b, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x6e,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x37, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x66, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2e, 0x72, 0x65,
	0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x31, 0x38, 0x6e, 0x54,
	0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x98, 0x01, 0x0a,
	0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2e, 0x72, 0x65, 0x75, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x10, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1d, 0x66, 0x72,
	0x61, 0x67, 0x6f, 0x65, 0x2f, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2f, 0x76,
	0x31, 0x3b, 0x72, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0xa2, 0x02, 0x05, 0x46, 0x47,
	0x52, 0x55, 0x53, 0xaa, 0x02, 0x13, 0x46, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x2e, 0x52, 0x65, 0x75,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x13, 0x46, 0x72, 0x61, 0x67,
	0x6f, 0x65, 0x5c, 0x52, 0x65, 0x75, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x5c, 0x56, 0x31, 0xea,
	0x02, 0x15, 0x46, 0x72, 0x61, 0x67, 0x6f, 0x65, 0x3a, 0x3a, 0x52, 0x65, 0x75, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fragoe_reusables_v1_picture_link_proto_rawDescOnce sync.Once
	file_fragoe_reusables_v1_picture_link_proto_rawDescData = file_fragoe_reusables_v1_picture_link_proto_rawDesc
)

func file_fragoe_reusables_v1_picture_link_proto_rawDescGZIP() []byte {
	file_fragoe_reusables_v1_picture_link_proto_rawDescOnce.Do(func() {
		file_fragoe_reusables_v1_picture_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_fragoe_reusables_v1_picture_link_proto_rawDescData)
	})
	return file_fragoe_reusables_v1_picture_link_proto_rawDescData
}

var file_fragoe_reusables_v1_picture_link_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fragoe_reusables_v1_picture_link_proto_goTypes = []interface{}{
	(*PictureLink)(nil), // 0: fragoe.reusables.v1.PictureLink
	(*I18NText)(nil),    // 1: fragoe.reusables.v1.I18nText
}
var file_fragoe_reusables_v1_picture_link_proto_depIdxs = []int32{
	1, // 0: fragoe.reusables.v1.PictureLink.caption:type_name -> fragoe.reusables.v1.I18nText
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fragoe_reusables_v1_picture_link_proto_init() }
func file_fragoe_reusables_v1_picture_link_proto_init() {
	if File_fragoe_reusables_v1_picture_link_proto != nil {
		return
	}
	file_fragoe_reusables_v1_i18n_text_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_fragoe_reusables_v1_picture_link_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fragoe_reusables_v1_picture_link_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fragoe_reusables_v1_picture_link_proto_goTypes,
		DependencyIndexes: file_fragoe_reusables_v1_picture_link_proto_depIdxs,
		MessageInfos:      file_fragoe_reusables_v1_picture_link_proto_msgTypes,
	}.Build()
	File_fragoe_reusables_v1_picture_link_proto = out.File
	file_fragoe_reusables_v1_picture_link_proto_rawDesc = nil
	file_fragoe_reusables_v1_picture_link_proto_goTypes = nil
	file_fragoe_reusables_v1_picture_link_proto_depIdxs = nil
}
